thkpd-pve1: ENC[AES256_GCM,data:aAVQlbT10LkmY03RRiHpPBp2o5D7ny6SVikv24QGen75f8/weEXO1T6c,iv:cmmSBDmUjAMiXybQXz6/+RI9S23GS5LsIt6lDGkQVpo=,tag:QF6o98RK7kKGWuLbcQ0StQ==,type:str]
vm-gameserver-nix: ENC[AES256_GCM,data:y0LUOjt6419dgk96eOrMBnp4xgTJkKVas2zbufF2HKR1AG0Z2d0+//gVUQ==,iv:x3LtuHwU1aiUW+wEJ3WT38n0lV2ZldG5bOI+AHGhoYE=,tag:Cxz66MxjQ2N4M9lhTd7bOw==,type:str]
ryzn-server: ENC[AES256_GCM,data:kVwtSv7ZGhG9h/X0DDgbzvO+ur5SR1sY2SeOIiUxGuJuL/T/hznRH1Gf,iv:kjzU2WWz8HktwTk1k0Goh50uSXw6dgOa4z7fg77CqAw=,tag:gsT4hCxWq1RN7MMpwynROw==,type:str]
simple-vm: ENC[AES256_GCM,data:AwQf2JTPlplD2zhOoofwh2rPEb5BT7bQzYZzLjmfxOTKFEUgGVzaJO7Ec7Kkfs54,iv:E76wloQNGC6IaRGHgt6rUYzcz8Z8TrQIOSZZCL9BLNI=,tag:g7n3A0GdGMoE6jAsZPKr6g==,type:str]
WorkOnlogic: ENC[AES256_GCM,data:8qZGOeHCRYNe8gwgP93ilVR0UZ9ZqcYtjPb64b+65odaTw==,iv:4LizUhQKP30w5B9YfvcDZ7XXTfq0oOWncRtDxx2qlfM=,tag:BfWKI46tlP/suVWbH8u0/w==,type:str]
linode-work: ENC[AES256_GCM,data:nVV81wNYJJhkp3oaN1y/u3XonuAMosI66114QVeAHxGGoMBEopDs8SpD1LF2tGez5EVOKRyBXoUSSTRU2FzJS856RqnOeIo=,iv:izC4Ye7iNt8YeTOXJ7wnCbzJVHeNTh3DG1N09+W1Kv4=,tag:gPZDICQXo9wDFM5JkI3ZCg==,type:str]
phoenix-router: ENC[AES256_GCM,data:+TKsn+7ETfHNgba5Z/uLr3rNtd4yeocu/kEY2MFsUVM=,iv:Gty/mYwWLrvmLDNyPute1x5qrNDOa4a3/0VzdkRpoOI=,tag:AUtFvdUmU1xcekMqCBUI/g==,type:str]
docs-server: ENC[AES256_GCM,data:5ux0elW0taJ0Qwe8sQjTyy3xxUPGCWqZY7xY96nf3GnWVpfV,iv:45rIrSWN1jLqqAi2KC7r6jWEHH1gqK0UEOQYIBSxOCY=,tag:w8pztECecyGoe/VFqvd3VA==,type:str]
devops-hypervisor: ENC[AES256_GCM,data:FWq+BAAoaWK8paY3ZF8y5mop/6tX7rFWudIzTdXsDSkW,iv:8fPZkRniLu3gu6P3gT4StNhQ3jMqXxyKCkJDL7Cb+Jc=,tag:ni+Oraly2VmdIAXon02cew==,type:str]
linux-dev-server: ENC[AES256_GCM,data:ZvK28CHG0tU1F+DWwEjfs4jgargqPGE1IsVzfz2ExMC9+BLI,iv:TiSv0yZQ75BoTdDwDaO9KWHT3YGcu6BXqgyTM7Efl8Y=,tag:k4ConUOVtqziJmJOJbm+rg==,type:str]
sys-galp-nix: ENC[AES256_GCM,data:m8d7iwLQO1EVt3zTNNNiOotCNCWo7sqpY6Z84k14t5W3PeTHUYuIMWiWdw==,iv:vDuzXVz9VqJofBC75GrBWAu/TimCrcPwzF6j1BRH6X0=,tag:1ncl05yOTFOpr9pUQcJWwQ==,type:str]
work-server: ENC[AES256_GCM,data:O/M6hgqVBffOVA85XXUygkeJrhJU/UCJ8jctQWB3wP//,iv:869Urkk6TWpFtb84w6XRYQo1mAamx634q48LuQiJZx0=,tag:+SX1yFgpCjpZKn8guYp20A==,type:str]
homeassistant: ENC[AES256_GCM,data:/v/NQO1tQB6ZjYm+8DVSQjNInFYQpsZWORvVq3RmY0Wd/Ol8Wpvl8DGPHQg2+iQL/hhzOgnc5nv2SobbCZzGr9B6YA3lYaw=,iv:2Xk7VmcUHIr4/WNMUb9QXNax8md5/PjH0yPEswe1KzU=,tag:j1WJbwnAJBClDMaRDQpRkg==,type:str]
frigate: ENC[AES256_GCM,data:lAMCyNbJlDmTwU2A+MSib0LfGEhXxdBN67ytK4nllnSB9YmRc9sRxawPdyNw8A==,iv:hry04b6s5peblbotvX/kGSUtUS6nXuExsw/BrxQrwAU=,tag:FKSA2re8el0MPRq06b0f3g==,type:str]
vm-docker-pri: ENC[AES256_GCM,data:n3YGXefcLXs08yTuAtoZYPwzUiBHzzEbLlo01bawYYGy8OruMfKHuJDZvFiElcYqU2HlhA==,iv:kLLXptUpt7UpRZfu7bqOrm66z3M0qmiJxVCJh4BTKlk=,tag:Oip+YMAgH2ouXPh7fIoUyw==,type:str]
docker1: ENC[AES256_GCM,data:kifd4ctFUnk3/SeS5pAv9QK7a2sZKZ8LszbW5+aYNkxO3qT+l257sxuHuZme+WgWjiFFMxeUZEGb1aGXjcQ=,iv:iVi2MwTTMoif24WfjcWS/MTUstI/WEoPLPuevMoEIxk=,tag:WB3Wv5h6QTMEkthVPKjurQ==,type:str]
docker2: ENC[AES256_GCM,data:ysJPiYuJNrnVhxS2untPNBYwBsjHG54Othzn84u30hnUM7gUgGjYPn3/sJ8z5spLPTb0vAIEg+lNXqllqfo=,iv:gL8A1WhSC9WQG1KrP8ZTELFlNS0zYeP+FgXL+9wcFkA=,tag:KhwpFlzb0VraY7ZSRa0gpw==,type:str]
docker3: ENC[AES256_GCM,data:5gbjcPh5CDFehtwuuyW/XoxvLP4alvoiLfMYzvrQDLId2Z+B6UR1oqAIKNz5hz6QQKM=,iv:a6J92Ilntzj0Kiy0OUtTTbsvtCN41g+9stf6bXK8ss8=,tag:mNgZ3aC5YxVCWR4lcemc7w==,type:str]
docker4: ENC[AES256_GCM,data:voUWRilmuuQmKcjo09uL6hL1mdv7DR8zAATtY1sAvzhIewruQ5p6S41sIa5DcWetKRYobfM=,iv:1PxH2GnRpvoyDP7xiLnr9/0m/JOV48DiZMW2mO+zzps=,tag:DIBGQGxuD4gYyPvconDF2g==,type:str]
opnsense: ENC[AES256_GCM,data:sJaRrU2ifRWk3H2J+iWJSmy54iN5AQc1H0K+aO0C9ZfehMNJrVf+kL5j30cQLM1WvV51jI0jgrOxVb6tfabnGSc=,iv:HwYAbIr3BeF/IxzZIj2Om7bHce2HwthhaLCWpOE3dG4=,tag:T79M7XLy2t5O11J1GoCemg==,type:str]
docker-pri: ENC[AES256_GCM,data:ROjprmvHoBoi9JXKAS6q7f0epfqTW+vOZCLjfT4e+nXuecsYGSMPsUwiMsFeYkWPKlwira606eFt31Sh,iv:HbneD04nkZqwSCXKOwggbQQ+1/NclkMC2GAqawykTqM=,tag:qOs4K6JDHiyDWGIfix1PIg==,type:str]
r610-pve1: ENC[AES256_GCM,data:7hOdBqI42jMgJB67DiKCDpeHZAf6hhpDQYt+GCYC4y5XbiDzAMP33ed2IzLMyNwUzCA3nrxBvCVYNctemKnl,iv:vgVn+m/qsQj8S7I2yLoPwfjr+C8b1U+nQFBmszqwVIM=,tag:qNTtW5/KrsCpKTg8KSDmIA==,type:str]
r610-pve2: ENC[AES256_GCM,data:iZxRVMvr7GHKlTV71/OW5hC3L7+l1tlyXwmOvVGr8xrbG4RzuPo1ZGEE3gfXXUg+dXlCwQAN8+iguwcL4YA5,iv:l2P0aUrSfHC6AbI+Lau/OhP72uiFA+PvEW60Film7u4=,tag:PHC19gQK11E9dBtyYghUtg==,type:str]
zb832-pve1: ENC[AES256_GCM,data:IXTZ1VOBnwn1M+d2Po4+HGWGfkmMeU222mC1t7YhHG9HPA==,iv:aBx91d1hnd6ypXtO22ttbNxga8dHpGjHMO+MVsDvs3c=,tag:v7nj0ZtPTR1cBg9Kr07YBQ==,type:str]
zb832-pve2: ENC[AES256_GCM,data:BYhjBJyA3E/qGjgTFQ/2P4vYyUPdKgNvOtwAqmlwdNhvFA==,iv:KsCLvMyh9vknean+T+6FuhGF7jIPf3ACtblSnlYy3FQ=,tag:cJLlhRK3NshkFRRSyWJzlg==,type:str]
zb432-pve1: ENC[AES256_GCM,data:KbDTjmN0R1oXvNNhkYRTB4YdVkCUvsHhkhkSEmpjYdWQqg==,iv:KJnldyF53ilmZiZ/ChZy1Vk4M93w2Jdd41A49WnIQ4A=,tag:2YhkIggggg3TAPPt316FzA==,type:str]
truenas: ENC[AES256_GCM,data:L3+xzsk8dsvVmIcH8ptgkKswKSvR1FTmhO5CDRuAq5d4m8XLcJp+kymu062ILttJJAeNm/QheTQ9wz1bFRQ=,iv:luN0DVdisVGqBPVK6jAezxCxUP6d+AiAlGVZwQU9t2s=,tag:+xAg1K5WGCx2tzv96ewPZQ==,type:str]
synlgy-ds918: ENC[AES256_GCM,data:rYcwj4Qcjsr1FrTgcKLSKqD2q1tkM9Povt9muOQTC1SUqPRekHH14PK/BrwMTAUPj01CqBykmvhv5uIcCujLe1v+ZCFD2A==,iv:IpIUKctUVNQ4R+pXEJlqed/bGehdUgM+XzEEu71t70o=,tag:hvKNa+gzUSptZ2ooYlhZ1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQmM1bndGNG1WMzE4RGJW
            Q3VReFd6Wit6R1M2N0JsNk4zQitEQjQweUU4CnFqaHVQcXRlY0VTVUI1enhXNEtQ
            MTRlSmhmMmxrdWhXOFBKM0NZczlWbUEKLS0tIGN4d1VrblZ5RzhXQ3N2STh2Z0dq
            M1hwdnNuRjdvK2N0Qzlaa21XNTQrVW8K4RkosgiExZcS2glUz6bYxqcqPL8UMdNU
            gR/8KIIaFOZa9t9+/F4SMrheFE67oOTZSMctUcRM4ubTRCtjJyP4WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sw9nqgpj8a0yz55k4ezsl040lx0u5ysqv7qzxkqldcmaugndl5fsqf4lc8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNjV6MHplL21scS84enBk
            M3ZNZWZjMjg5NkZMYllvdXNaa2VwbDJFZ1ZNCkNRellHMDhzS1J5a01TT3JrVS9r
            dFpFUVhkNkFGaHJ4V1NqcUhnOUh6bDAKLS0tIDB1NkpaeElFWk5icFdvRHVVMlk4
            N3puRTIvZkh2YUNsREJNVXRsZ2RLclEKNVpiWmzAlJCrDfSeZbWxIgABeVdHG1eo
            3IRj7bVyOyLJZQr7ToLrj/Dqm0gqza3uh/WUim6LkXH+Gh3f278qzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g98hga3gn0qmtelwmcm3gpfpjpmt6zs60xww2vj7fk4v8n48qc5shnnvq3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc1ExWG9jNjkwdVRmcVRK
            aHgvWGQyRHNDNlBQTUI1SzZUcDFEQXV0bHhrCnUzWlZzLzE1TVVLbVJ6Q0lobFBl
            R1BJaXhwNDUySGM5aXJCbi9ueklISU0KLS0tIE1WNmMyWDEvbExRTk55d2dkRFRH
            c3VwYW42LzlUYzFVeUNHYnh0M0pnbXcKsxG4qMDoqQ3K1JHNzR5+LO2z7jLd88Ir
            usIQgOD4ZhCMzt8vObMrNs+1wjnipkPf+j5mOTNKcAxRTbzUAv/UsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w04gmlhglqns8sqvq9e4h85hggph8028n7xn6n7tz20nh23wxezsvm5n0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ckkwck1MUlVjcXIwMDVY
            UDFCZys2QVJBM1ZVb0pXb1AxMmxhY2RPNFFRCk01OGRwVEJtK0RRTmxvb1dLZmRl
            TGRGMUVvTnA0V0ZzK2VEZWRnTGNrYlEKLS0tIENRYVlHMk4yRkxCWGZoeG9zN054
            bFNocE5RNWZqV0dnWlBNV1ZvWnRYL0EKdz0EqjV7kxaP0NLZnH9QgRkAceDN7G5D
            Amp/bZbi9AOrPecD4q/84I87oa01D1Zt8D5xVfby6g7sE2OQxBmNRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15tde43t4ms7k24xhewrt58eznfn6l3vht70gxmmpg4j5ykm2n4uqt20ga0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SEJ0RncrUlBVc3NNNUxG
            cVg1R05zcEFxT2t4WURnVzA2Y1QxTXBlQWtVCmlIMEVwb1FpL2R1V3NKVlUxVERE
            ME1lbkFGQk1SZWMxTGU1aUJERTI3eEkKLS0tIG80Slg4dHNyWDlmNllFTUluWFN2
            bE9nc0lLdjF5dWFpZTREaTFEU3BCdlkKNoGgBPV0Nq6DO68Zi9WYS9I12drqJMrH
            0h0N33MRUb+Hj7/ZoDJCLYeRKNPJKI4Qva5WL+tPAqB34S5a+9sgow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exdsgk0hlf47ks2qf7jyls7k7q52e2d82306f3w859vyv3vqna5s4qygyc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WUluaDBBUmRnMU1RYm9p
            U1NqRGZhcWU3ZDQ5YkFHRy9rY2ZxVHovZUNjCnBReDl3ME40OVdCdlhUMys3Witp
            RnpSYVV3emNuanBiU2RvTzlRVWxYb2sKLS0tIEtEazRQcjY3b0Nyc3JYYkV6SUt2
            VFpFb2tjald4bVN2MUFYZi9hSU4xM0kKld9Lbb8f37LEUGKspE0+Bz/MZ3hbtkA1
            BTT6kSMYxSpluiMrdEsFuSVDjQR4fmBMX//yMC7BPr1Y8I9tLraMSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdcaucwsf52y0ak9uv8lr48p20tu407lasw9rlddd894qfluhptsy05adf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNUZlalEwRHhiOUxKVG1p
            ZVVuakRnM2hFWFd6Qmk0dGwzcW1YbXhELzJrCmFhaC9iRXpuNDdzNlFQSEgyVzF6
            bHVyQURzZVlQL2lTOWRBZDV5TEZEZGcKLS0tIGV1STgwMmtWWVZrNjdycytrUUdm
            NFBlTnVteXlKdmgrTEJSODhOUDZnUUkKpJKtlcstIm8OY71JHFIViAqybf5V6i2X
            yHfI1oggP/P0I9u0kgF/ZvDZfyVNRoMW3hEH7vmIVsaw9qR9Uk26AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rfh8tflpx2d0j6p00284t4ep7tsqut2c9uz58ljw2k0lvr08vqtqklzqv8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUUZVaEJ6YmJtaWx3Y21p
            V2pqMGRycWxUcmtjMmdHVU4wWW5TR2VsVUZBCjcrRzZRTkhGa0J0alIxVVpmN1J0
            dFNMZG9GbTNOY2s0K2drS3gveGlvNmcKLS0tIGxyUzZTemVJRFJJS1lFYjVIUkwx
            d3ZibXh6ek1pbFZzWlI0MWhNcE5vVGMKe5Afa6/DQS6vEWduRSsHLev0v2hOPpWp
            5HB95MQzwMRqSC4ISgU3o9So7o/Bf7hAlUfFs8v6CJX/aa9YHJj4WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12kq643k846phl8zx4n30q486z2n3wf5y73qvqhd6e8e5ks62tq3sds4xqu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z3pxeHFvTnN3eWttSEZt
            Zm1MQ3VDNEMrWk1lL1Q3YmQ3K2Q1aFRkT1QwClA0ZjRSQ05PbXUwVFFmZjU3VDF6
            SG1TaHVxTE93T3RIL2lMN0lhcE1EaFEKLS0tIFJSU2tPRW8vQzgzTkU5QThwaEtE
            MVMydy82bWdQc2h3bXMrb3dkTXNhUWcKpqa51FeLIXmg5KmLl8AFqeb7PUqjK+jG
            aTTS6GeuGSu7DbQJ7tkyB+R0ViQWZZx0H6G0rBcpcLLEHNAaoB/aLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qfe2h4mxt66lplx3vzcyz88wux0n7vqegy2wu0hg29fy7apjtqlqnr5fw6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ylcxcm5BRW1TNWwwSjE5
            UVpkMzVjVHNXZ201ZGV6QWtxeXAyVzFja0ZZCjJtYmdqRHViUThPaXU3TERTYU0v
            RFl4UU1mYzNCeTgrNW9Ma2dPSFlvKzAKLS0tIFI1dmw5WVp1b2VWYWNuSG8yZ3M1
            YVZvd3RUdUVob3lKUjcycEJjODkzWm8KBHC5kCrGqM7cdoAeX4HpxM8ccDzDEPmi
            e2tEa0FUr7CEhTYJ7xs6m0CWYlxlZ/MeWS5CV3zFzLs/qFiYAlThrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxs6p30u9spu7fq0n42720c8e7pln6y2t2ffet0mktp88cyfu3vqv9yazp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eUxoekFTalNjUHJiWUlC
            VGtGRWpjbUlLVVRneElncVVEcHlaS1h2TlI0CkpXV3p4WGlNR05HaUhpOW80eVFt
            R1ZpWFFOUElqSHdkVWlYQTA4K2NLeWcKLS0tIGtCVGMzejJjU0JsMzRUYVZQMDBl
            c3B3WEhuY0VXd3ZlckJ1QWJoL2U0WTAKUgiQFEi3ESRA9Q3nl1mwpawfGrRAK/Qj
            4QoD37RRhut6MgEWCx5/z4UP4Ja/biUIbUaKkE2CiD6jm/LR8H6RQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6nk6g2yt06ccqm7ptzlqpa2ve73z7cyzyvdnv67eh49zm3thqhszhx6x0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbDFiNmt0WVZHeVRPOUFZ
            V3BzYWMycjZ5cHo4aUM0WWRXc1hJZHJoRkJJCmJkQk1ocjRnTXRpVk9Ncm9aY24r
            anNzWnBLRjZrRmdOZUlHSDJpQTZMSkEKLS0tIEM1MjB2dndob3JmQUdLdmRDVHMv
            b2lwZlU3OWNYSlhsZXJqWW80SU9SWk0KKWj9qIUVdfTougOtndLiVcxSRQ3rRHP6
            vv+zExNX221gj/r+el3yIx0s9BKL02jVOTowN5kX7fgCQ1t1IvpWHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z554l6fxpcymp6rfv82s72m2erfh0uj5uj9hkrjj06nwcj46qu9q6l0hjs
    lastmodified: "2026-08-28T07:56:15Z"
    mac: ENC[AES256_GCM,data:69P7kzaN6bk3OClbNBaYMDwAzUxASUA8vVKLeB+0a60Y+mi1yl08dZtS+eUJHYaqtGfdOz3jXV310E2P6xRQoY7DhCAnkwZdkyBS92H9VyaCpxIZThOV2bxwI61wQcqFD6IIOwMrjGc8ggUeH0EODA1ur4MdbZJSHaOcpVADud4=,iv:Zgwxpn9krPh0lJXUe6y/mu6LqyyVGpeQAFG2RHo/Skg=,tag:Vc4GajTaznmPimNn5YEQqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
