{
  inputs,
  ...
}:
{
  imports = [
    ./core/profiles/default.nix
    ./core/traits/default.nix
    ./core/system/default.nix
    ./core/users/default.nix
    ./core/nix-settings/default.nix

    ./features/ai/default.nix
    ./features/attic/default.nix
    ./features/cloudflared/default.nix
    ./features/compose/default.nix
    ./features/desktop/default.nix
    ./features/sound/default.nix
    ./features/fonts/default.nix
    ./features/networking/default.nix
    ./features/printing/default.nix
    ./features/ssh/default.nix
    ./features/sops/default.nix
    ./features/graphics/default.nix
    ./features/docker/default.nix
    ./features/tailscale/default.nix
    ./features/traefik/default.nix
    ./features/searxng/default.nix
    ./features/flatpak/default.nix
    ./features/packages/default.nix
    ./features/filesystems/default.nix
    ./features/bluetooth/default.nix
    ./features/gaming/default.nix
    ./features/vscode/default.nix
    ./features/vpn/default.nix
    ./features/security/default.nix
    ./features/wine/default.nix
    ./features/proxmox/default.nix
    ./features/cachix/default.nix
    ./features/1password/default.nix
    ./features/gameserver/default.nix
    ./features/sunshine/default.nix
    ./features/syncthing/default.nix

    inputs.nix-flatpak.nixosModules.nix-flatpak
  ];
}
