# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &bitwarden age1sw9nqgpj8a0yz55k4ezsl040lx0u5ysqv7qzxkqldcmaugndl5fsqf4lc8
  - &razer-nixos age1g98hga3gn0qmtelwmcm3gpfpjpmt6zs60xww2vj7fk4v8n48qc5shnnvq3
  - &work-wsl age19ajzg046l44kdnmnc67hrffjdk8d4ufhc5luj2cf0zwrdj9ztq3ssw2rqu
  - &work-jdguillot age1exdsgk0hlf47ks2qf7jyls7k7q52e2d82306f3w859vyv3vqna5s4qygyc
  - &ryzn-nixos-wsl age1qdcaucwsf52y0ak9uv8lr48p20tu407lasw9rlddd894qfluhptsy05adf
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *bitwarden
          - *razer-nixos
          - *work-wsl
          - *work-jdguillot
          - *ryzn-nixos-wsl
