{
  imports = [
    ./git/default.nix
    ./shell/default.nix
    ./noctalia/default.nix
    ./dank/default.nix
    ./niri/default.nix
    ./sops/default.nix
    ./editor/default.nix
    ./terminal/default.nix
    ./desktop/default.nix
    ./ssh/default.nix
    ./tools/default.nix
    ./tools/btop/default.nix
    ./tools/mcp/default.nix
    ./tools/agent-browser/default.nix
    ./tools/lsp/default.nix
    ./tools/skills/default.nix
    ./tools/claude-code/default.nix
    ./tools/lazygit/default.nix
    ./tools/midnight-commander/default.nix
    ./tools/opencode/default.nix
    ./tools/crush/default.nix
    ./tools/tmuxai/default.nix
    ./tools/rofi/default.nix
    ./tools/sesh/default.nix
    ./tools/jujutsu/default.nix
    ./tools/carapace/default.nix
    ./tools/tmux/default.nix
    ./tools/tmux/tmuxinator.nix
    ./tools/zellij/default.nix
    ./tools/yazi/default.nix
    ./tools/direnv/default.nix
    ./tools/fastfetch/default.nix
  ];
}
