-- nixd resolves NixOS options against one flake attribute at a time, so pinning
-- it to the machine you happen to be sitting at gives wrong hovers, completions
-- and go-to-definition while editing another host's configuration.nix.
--
-- The target host follows the current buffer: hosts/<name>/ is the flake
-- attribute of that host, checked against .nixd-hosts.json (generated by the
-- lazyvim home-manager module). :NixdHost pins it manually.

local dotfiles = vim.env.HOME .. "/.dotfiles"

-- { default = "<flake attr>", hosts = { <flake attr> = { home = ... } } }
local map = { default = vim.fn.hostname(), hosts = {} }
do
  local ok, lines = pcall(vim.fn.readfile, dotfiles .. "/.nixd-hosts.json")
  if ok then
    local decoded_ok, decoded = pcall(vim.json.decode, table.concat(lines, "\n"))
    if decoded_ok and type(decoded) == "table" and type(decoded.hosts) == "table" then
      map = decoded
    end
  end
end

local function host_for_path(path)
  if not path or path == "" then
    return nil
  end
  local name = vim.fs.normalize(vim.fn.fnamemodify(path, ":p")):match("/hosts/([^/]+)/")
  return name and map.hosts[name] and name or nil
end

local function settings_for(host)
  local meta = map.hosts[host] or {}
  local hm = meta.home or ((vim.env.USER or "") .. "@" .. host)
  return {
    nixd = {
      nixpkgs = {
        expr = string.format("import (builtins.getFlake %q).inputs.nixpkgs { }", dotfiles),
      },
      formatting = {
        command = { "nixfmt" },
      },
      options = {
        nixos = {
          expr = string.format("(builtins.getFlake %q).nixosConfigurations.%q.options", dotfiles, host),
        },
        home_manager = {
          expr = string.format("(builtins.getFlake %q).homeConfigurations.%q.options", dotfiles, hm),
        },
      },
    },
  }
end

local active = host_for_path(vim.api.nvim_buf_get_name(0)) or map.default
local pinned = false

local function apply(host)
  active = host
  local settings = settings_for(host)
  -- Seed the config used by any future client...
  pcall(function()
    vim.lsp.config("nixd", { settings = settings })
  end)
  -- ...and re-point the running ones in place; nixd re-pulls its configuration
  -- when notified, so this avoids a server restart.
  for _, client in ipairs(vim.lsp.get_clients({ name = "nixd" })) do
    client.settings = settings
    client:notify("workspace/didChangeConfiguration", { settings = settings })
  end
end

-- nixd only resolves attrpaths that name a real option declaration. Namespace
-- nodes like `cyberfighter.features` have no `declarations` -- they are implied
-- by the modules that declare options beneath them -- so gd comes back empty.
-- Fall back to grepping for the declaration site in that case.

--- Rebuild the option attrpath the cursor sits on, e.g. "cyberfighter.features".
--- Only components up to the cursor are kept, so gd on `features` in
--- `features.desktop.firefox` asks about `cyberfighter.features`.
local function attrpath_at_cursor(bufnr, row, col)
  -- Drive the parser directly rather than vim.treesitter.get_node, which only
  -- works once something else (highlighting) has attached one to the buffer.
  local ok, parser = pcall(vim.treesitter.get_parser, bufnr, "nix")
  if not ok or not parser then
    return nil
  end
  local tree = parser:parse()[1]
  if not tree then
    return nil
  end
  local node = tree:root():named_descendant_for_range(row, col, row, col)
  if not node then
    return nil
  end

  local attrpath = node
  while attrpath and attrpath:type() ~= "attrpath" do
    attrpath = attrpath:parent()
  end
  if not attrpath then
    return nil
  end

  local parts = {}
  for child in attrpath:iter_children() do
    if child:named() then
      parts[#parts + 1] = vim.treesitter.get_node_text(child, bufnr)
      local _, _, end_row, end_col = child:range()
      if row < end_row or (row == end_row and col < end_col) then
        break
      end
    end
  end

  -- Every enclosing binding contributes an outer prefix.
  local parent = attrpath:parent()
  while parent do
    if parent:type() == "binding" then
      local outer = parent:field("attrpath")[1]
      if outer and outer:id() ~= attrpath:id() then
        local prefix = {}
        for child in outer:iter_children() do
          if child:named() then
            prefix[#prefix + 1] = vim.treesitter.get_node_text(child, bufnr)
          end
        end
        parts = vim.list_extend(prefix, parts)
      end
    end
    parent = parent:parent()
  end

  return #parts > 0 and table.concat(parts, ".") or nil
end

local function grep_declaration(attrpath)
  local needle = "options." .. attrpath
  if Snacks and Snacks.picker then
    Snacks.picker.grep({
      cwd = dotfiles,
      search = needle,
      regex = false,
      live = false,
      title = "declarations of " .. attrpath,
    })
    return true
  end
  local hits = vim.fn.systemlist({ "rg", "--vimgrep", "--fixed-strings", needle, dotfiles })
  if vim.v.shell_error ~= 0 or #hits == 0 then
    return false
  end
  vim.fn.setqflist({}, " ", { title = needle, lines = hits })
  vim.cmd("copen")
  return true
end

local function goto_definition()
  local buf = vim.api.nvim_get_current_buf()
  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
  local client = vim.lsp.get_clients({ bufnr = buf, name = "nixd" })[1]
  local params = vim.lsp.util.make_position_params(0, client and client.offset_encoding or "utf-16")

  vim.lsp.buf_request_all(buf, "textDocument/definition", params, function(responses)
    for _, response in pairs(responses or {}) do
      local result = response.result
      if result and (result.uri or result.targetUri or #result > 0) then
        -- Hand off to LazyVim's usual picker rather than reimplementing its
        -- jump/pick behaviour; the second request is cheap once nixd is warm.
        return Snacks.picker.lsp_definitions()
      end
    end

    local attrpath = attrpath_at_cursor(buf, row - 1, col)
    if attrpath and grep_declaration(attrpath) then
      return
    end
    vim.notify("nixd: no definition for " .. (attrpath or "cursor"), vim.log.levels.WARN)
  end)
end

vim.api.nvim_create_autocmd("LspAttach", {
  group = vim.api.nvim_create_augroup("nixd_definition_fallback", { clear = true }),
  callback = function(ev)
    local client = vim.lsp.get_client_by_id(ev.data.client_id)
    if not client or client.name ~= "nixd" then
      return
    end
    -- Deferred so this lands after LazyVim's own LspAttach keymaps.
    vim.schedule(function()
      if vim.api.nvim_buf_is_valid(ev.buf) then
        vim.keymap.set("n", "gd", goto_definition, {
          buffer = ev.buf,
          desc = "Goto Definition (nixd, falls back to option declaration grep)",
        })
      end
    end)
  end,
})

vim.api.nvim_create_autocmd("BufEnter", {
  group = vim.api.nvim_create_augroup("nixd_host_follow", { clear = true }),
  pattern = "*.nix",
  callback = function(ev)
    if pinned then
      return
    end
    local host = host_for_path(ev.file)
    if host and host ~= active then
      apply(host)
      vim.notify("nixd: options now resolved against " .. host, vim.log.levels.INFO)
    end
  end,
})

vim.api.nvim_create_user_command("NixdHost", function(cmd)
  local host = vim.trim(cmd.args)
  if host == "" then
    vim.notify(("nixd host: %s (%s)"):format(active, pinned and "pinned" or "follows buffer"))
  elseif host == "auto" then
    pinned = false
    apply(host_for_path(vim.api.nvim_buf_get_name(0)) or map.default)
    vim.notify("nixd host: following buffer (" .. active .. ")")
  elseif not map.hosts[host] then
    vim.notify("nixd: unknown host " .. host, vim.log.levels.ERROR)
  else
    pinned = true
    apply(host)
    vim.notify("nixd host pinned to " .. host)
  end
end, {
  nargs = "?",
  desc = "Select the flake host nixd resolves NixOS options against",
  complete = function(lead)
    local names = { "auto" }
    for attr in pairs(map.hosts) do
      names[#names + 1] = attr
    end
    table.sort(names)
    return vim.tbl_filter(function(name)
      return name:find(lead, 1, true) == 1
    end, names)
  end,
})

return {
  {
    "neovim/nvim-lspconfig",
    opts = function(_, opts)
      opts.servers = opts.servers or {}
      opts.servers.nixd = vim.tbl_deep_extend("force", {
        cmd = { "nixd" },
      }, { settings = settings_for(active) })
      return opts
    end,
  },
}
