# Auto-generated by compose2nix.

{ lib, ... }:

{
  # Containers
  virtualisation.oci-containers.containers."stirling-pdf-stirling-pdf" = {
    image = "stirlingtools/stirling-pdf:latest";
    environment = {
      "DOCKER_ENABLE_SECURITY" = "false";
      "INSTALL_BOOK_AND_ADVANCED_HTML_OPS" = "false";
      "LANGS" = "en_GB";
    };
    volumes = [
      "/home/cyberfighter/docker/stirling/extraConfigs:/configs:rw"
      "/home/cyberfighter/docker/stirling/trainingData:/usr/share/tessdata:rw"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.pdf.rule" = "Host(`pdf.cyberfighter.space`)";
      "traefik.http.routers.pdf.service" = "pdf-svc";
      "traefik.http.routers.pdf.tls" = "true";
      "traefik.http.routers.pdf.tls.certResolver" = "lets-encrypt";
      "traefik.http.services.pdf-svc.loadbalancer.server.port" = "8080";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=stirling-pdf"
      "--network=web"
    ];
  };
  systemd.services."podman-stirling-pdf-stirling-pdf" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "podman-compose-stirling-pdf-root.target"
    ];
    wantedBy = [
      "podman-compose-stirling-pdf-root.target"
    ];
    after = [ "podman-network-web.service" ];
    requires = [ "podman-network-web.service" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-stirling-pdf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
