# Auto-generated by compose2nix.

{ lib, ... }:

{
  # Containers
  virtualisation.oci-containers.containers."traefik" = {
    image = "traefik";
    environment = {
      "CF_API_EMAIL" = "cyberfighter@gmail.com";
      "CF_DNS_API_TOKEN_FILE" = "/run/secrets/CF_ZONE_DNS_API_TOKEN";
      "CF_ZONE_API_TOKEN_FILE" = "/run/secrets/CF_ZONE_DNS_API_TOKEN";
    };
    volumes = [
      "/home/cyberfighter/docker/traefik/acme.json:/acme.json:rw"
      "/home/cyberfighter/docker/traefik/traefik.toml:/traefik.toml:ro"
      "/home/cyberfighter/docker/traefik/traefik_dynamic/:/traefik_dynamic:ro"
      "/var/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "80:80/tcp"
      "443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=traefik"
      "--network=web"
    ];
  };
  systemd.services."podman-traefik" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-traefik-root.target"
    ];
    wantedBy = [
      "podman-compose-traefik-root.target"
    ];
    after = [ "podman-network-web.service" ];
    requires = [ "podman-network-web.service" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-traefik-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
