# .github/workflows/cachix.yml
name: Build and Cache
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  actions: write

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            connect-timeout = 30
            fallback = true
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 4G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-last-accessed: P1DT12H
          purge-primary-key: never
      - uses: cachix/cachix-action@v15
        with:
          name: jdguillot
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Perform Flake check
        run: nix flake check

  build:
    needs: flake-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          [
            razer-nixos,
            work-nix-wsl,
            nixos-portable,
            ryzn-nix-wsl,
            sys-galp-nix,
            thkpd-pve1,
          ]
      fail-fast: false # Continue other builds if one fails
    steps:
      - uses: actions/checkout@v6
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            connect-timeout = 30
            fallback = true
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.host }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ matrix.host }}-
          gc-max-store-size-linux: 4G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-${{ matrix.host }}-
          purge-last-accessed: P1DT12H
          purge-primary-key: never
      - uses: cachix/cachix-action@v15
        with:
          name: jdguillot
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Systems
        run: |
          nix build --fallback .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
